# Generated by Django 5.1.5 on 2025-02-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_type', models.CharField(choices=[('Handheld', 'Handheld'), ('Home Console', 'Home Console'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('console_model', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(choices=[('NTSC', 'NTSC'), ('PAL', 'PAL'), ('Region-Free', 'Region-Free')], max_length=15)),
            ],
        ),
    ]
