# Generated by Django 5.1.5 on 2025-02-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_console_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='console',
            table='consoles',
        ),
    ]
